"""Rasterise Natural Earth admin-1 regions onto the analysis grid.

Emits two small files the hover readout indexes directly:
  src/textures/admin.png   16-bit region id packed into the R,G channels,
                           on exactly the grid in engine_constants.js
  src/admin_names.js       window.ADMIN = {names: {id: "Region, Country"}}

The id raster is CPU-only (never uploaded to the GPU), so the encoding just
has to survive PNG round-tripping: id = R + 256*G, 0 = no region.

Coastal cells whose centre falls outside every polygon (the analysis grid is
coarser than the coastline) are filled from the nearest labelled cell, bounded
to a few cells so open ocean stays unlabelled. Natural Earth is public domain.

Usage: python3 scripts/build_admin_lookup.py [path/to/ne_10m_admin_1_states_provinces.zip]
Downloads to a temp dir if no path is given; the raw zip is never kept.
"""
from __future__ import annotations

import json
import re
import sys
import tempfile
import urllib.request
from pathlib import Path

import geopandas as gpd
import numpy as np
from PIL import Image
from rasterio import features
from rasterio.transform import from_origin
from scipy import ndimage

ROOT = Path(__file__).resolve().parent.parent
NE_URL = ("https://naciscdn.org/naturalearth/10m/cultural/"
          "ne_10m_admin_1_states_provinces.zip")
COAST_FILL_CELLS = 3          # how far offshore a cell centre may sit and
                              # still inherit the nearest region's name

# The readout is ~270 px wide; shorten the long-form country names that
# Natural Earth uses. Display names only — ids and geometry are untouched.
SHORT_COUNTRY = {
    "United States of America": "United States",
    "United Republic of Tanzania": "Tanzania",
    "Democratic Republic of the Congo": "DR Congo",
    "Central African Republic": "C.A.R.",
    "Bosnia and Herzegovina": "Bosnia and Herz.",
    "Federated States of Micronesia": "Micronesia",
    "Saint Vincent and the Grenadines": "St. Vincent",
    "South Georgia and the Islands": "South Georgia",
}


def grid_from_engine_constants() -> dict:
    txt = (ROOT / "src/engine_constants.js").read_text()
    payload = json.loads(txt[txt.index("{"):txt.rindex(";")])
    return payload["grid"]


def main() -> None:
    if len(sys.argv) > 1:
        zip_path = Path(sys.argv[1])
        tmp = None
    else:
        tmp = tempfile.TemporaryDirectory()
        zip_path = Path(tmp.name) / "ne_admin1.zip"
        print(f"downloading {NE_URL}")
        urllib.request.urlretrieve(NE_URL, zip_path)

    g = grid_from_engine_constants()
    w, h = g["width"], g["height"]
    transform = from_origin(g["west"], g["north"], g["dlon"], g["dlat"])

    gdf = gpd.read_file(f"zip://{zip_path}")
    # "name" is the admin-1 unit, "admin" the country. A few dependencies have
    # a null name; fall back to the country alone rather than dropping them.
    labels = []
    for _, row in gdf.iterrows():
        country = SHORT_COUNTRY.get(row["admin"], row["admin"])
        labels.append(f"{row['name']}, {country}" if row["name"] else country)
    # ids are 1-based; 0 is "no region".
    shapes = ((geom, i + 1) for i, geom in enumerate(gdf.geometry))
    ids = features.rasterize(
        shapes, out_shape=(h, w), transform=transform, fill=0, dtype="uint32",
        all_touched=False,
    )

    # Nearest-region fill for near-coast cells, bounded so ocean stays 0.
    dist, (iy, ix) = ndimage.distance_transform_edt(
        ids == 0, return_indices=True)
    near = ids[iy, ix]
    ids = np.where((ids == 0) & (dist <= COAST_FILL_CELLS), near, ids)

    n_max = int(ids.max())
    assert n_max < 65536, f"{n_max} regions exceeds the 16-bit encoding"
    rgba = np.zeros((h, w, 4), dtype=np.uint8)
    rgba[..., 0] = ids & 0xFF
    rgba[..., 1] = (ids >> 8) & 0xFF
    rgba[..., 3] = 255        # opaque everywhere; premultiply cannot corrupt
    out_png = ROOT / "src/textures/admin.png"
    Image.fromarray(rgba).save(out_png, optimize=True)

    used = sorted(set(np.unique(ids)) - {0})
    names = {str(i): labels[i - 1] for i in used}
    out_js = ROOT / "src/admin_names.js"
    out_js.write_text(
        "/* GENERATED by scripts/build_admin_lookup.py from Natural Earth 10m\n"
        "   admin-1 (public domain). Do not edit. */\n"
        "window.ADMIN = " + json.dumps({"names": names}, ensure_ascii=False,
                                        separators=(",", ":")) + ";\n")

    kb = out_png.stat().st_size / 1024, out_js.stat().st_size / 1024
    print(f"admin.png {kb[0]:.0f} KB, admin_names.js {kb[1]:.0f} KB, "
          f"{len(used)} of {len(labels)} regions present on the grid")
    if tmp:
        tmp.cleanup()


if __name__ == "__main__":
    main()
