/* GENERATED by scripts/build_v0.py from scripts/constants.py.
   Do not edit. Edit constants.py and rebuild. */
window.ERW = {
  "grid": {
    "width": 3600,
    "height": 1400,
    "west": -179.99836080934742,
    "north": 82.71928405344525,
    "dlon": 0.09999800630262258,
    "dlat": 0.0990689892669193
  },
  "terms": [
    {
      "key": "reactivity",
      "label": "Dissolution rate",
      "hint": "Palandri-Kharaka Ca+Mg release, relative to pH 6.5 / 15 C"
    },
    {
      "key": "eta_dic",
      "label": "Alkalinity retained as DIC",
      "hint": "Carbonate-equilibrium efficiency: what share of released alkalinity is actually held as dissolved inorganic carbon"
    },
    {
      "key": "drainage",
      "label": "Drainage / transport",
      "hint": "q/(q+Dw) on WaterGAP recharge; low where water residence limits export"
    }
  ],
  "epsQuantize": 0.02,
  "aggP": 0.0,
  "ramp": [
    [
      0.0,
      "#3b1f4d"
    ],
    [
      0.2,
      "#3d4a8f"
    ],
    [
      0.4,
      "#2a7b8f"
    ],
    [
      0.6,
      "#3fa66b"
    ],
    [
      0.8,
      "#a8c93a"
    ],
    [
      1.0,
      "#f7e94a"
    ]
  ],
  "rampFrac": [
    [
      0.0,
      "#1c1233"
    ],
    [
      0.07,
      "#3a1a5c"
    ],
    [
      0.14,
      "#5e1f79"
    ],
    [
      0.28,
      "#8c2981"
    ],
    [
      0.5,
      "#c9457b"
    ],
    [
      0.75,
      "#f1705d"
    ],
    [
      1.0,
      "#fdc98a"
    ]
  ],
  "cdrKnots": [
    [
      0.02,
      0.0
    ],
    [
      0.1,
      0.2
    ],
    [
      0.5,
      0.4
    ],
    [
      1.5,
      0.6
    ],
    [
      4.0,
      0.8
    ],
    [
      10.0,
      1.0
    ]
  ],
  "cdrNegligible": 0.02,
  "dissolvedFracAtRef": 0.25,
  "dissolvedFracObserved": [
    0.15,
    0.56
  ],
  "termExponent": {
    "default": 1.0,
    "range": [
      0.0,
      1.0
    ]
  },
  "cdrPerFrac": 8.69118,
  "l1Enc": {
    "lo": -3.0,
    "hi": 3.0
  },
  "fluxCeiling": {
    "on": true,
    "enc": {
      "lo": -4.0,
      "hi": 0.3
    },
    "omega": 10.0,
    "omegaStrict": 1.0,
    "omegaRange": [
      1.0,
      10.0
    ],
    "fCa": 0.5,
    "source": "calcite saturation at the cell's own soil pCO2 and temperature, with charge balance 2[Ca]+2[Mg] = [HCO3-]; Plummer & Busenberg 1982 constants. Omega < 10 inhibition after Zhang et al. 2022, Limnol. Oceanogr. 67, doi:10.1002/lno.12244",
    "anchors": {
      "Zhang 2022 riverine CTP, back-converted": [
        4.3,
        13.0
      ],
      "Hamilton 2007 Midwest tile drainage / porewater": [
        1.0,
        7.0
      ],
      "Meybeck pristine rivers, 99th percentile": [
        5.95,
        5.95
      ],
      "Meybeck carbonate-terrain streams": [
        3.15,
        3.15
      ],
      "field trials, ACHIEVED under ERW (not a ceiling)": [
        0.11,
        0.75
      ]
    },
    "bindsAreaFrac": 0.9893,
    "medianTco2HaYr": 0.2202,
    "warmCoolUncapped": 4.37,
    "warmCoolCeiling": 0.91,
    "realisedShareOfStoich": 0.0253
  },
  "damkohler": {
    "dw": 0.03,
    "dwRange": [
      0.001,
      0.3
    ],
    "tau": 7.3891,
    "tauInEta": false,
    "source": "Maher & Chamberlain 2014, Science 343, 1502 (Fig. 2 contours)"
  },
  "psd": {
    "refD50": 150.0,
    "refWidth": 1.5,
    "d50Range": [
      40.0,
      700.0
    ],
    "widthRange": [
      0.7,
      2.5
    ],
    "refSsa": 0.02572,
    "lambdaDefault": 27.5,
    "lambdaMeasured": 27.5,
    "lambdaBasis": "Gudbrandsson et al. 2011: 45-125 um sieve fraction with fines removed, 0.703 m2/g krypton BET, implied d80 109 um",
    "betMeasured": 0.703,
    "refWidthNarrowForCrush": true,
    "lambdaRange": [
      1.0,
      100.0
    ],
    "deliveryRangeUm": [
      67.0,
      600.0
    ],
    "deliveryP50": {
      "mati": 600.0,
      "terradot": 120.0,
      "lithos": 67.0
    },
    "refWidthAssumed": true,
    "d50Grid": [
      40.0,
      67.5,
      95.0,
      122.5,
      150.0,
      178.9,
      207.9,
      236.8,
      265.8,
      294.7,
      323.7,
      352.6,
      381.6,
      410.5,
      439.5,
      468.4,
      497.4,
      526.3,
      555.3,
      584.2,
      613.2,
      642.1,
      671.1,
      700.0
    ],
    "widthGrid": [
      0.7,
      0.86,
      1.02,
      1.18,
      1.34,
      1.5,
      1.643,
      1.786,
      1.929,
      2.071,
      2.214,
      2.357,
      2.5
    ],
    "shiftTable": [
      [
        0.7779,
        0.6481,
        0.561,
        0.4952,
        0.4423,
        0.396,
        0.3563,
        0.322,
        0.2917,
        0.2647,
        0.2403,
        0.2183,
        0.1981,
        0.1797,
        0.1626,
        0.1469,
        0.1323,
        0.1187,
        0.1059,
        0.094,
        0.0828,
        0.0723,
        0.0623,
        0.0529
      ],
      [
        0.7268,
        0.5738,
        0.471,
        0.3932,
        0.3304,
        0.2754,
        0.228,
        0.1868,
        0.1501,
        0.1171,
        0.0871,
        0.0598,
        0.0345,
        0.0112,
        -0.0105,
        -0.0307,
        -0.0497,
        -0.0674,
        -0.0841,
        -0.0998,
        -0.1147,
        -0.1287,
        -0.142,
        -0.1546
      ],
      [
        0.674,
        0.5012,
        0.3852,
        0.2975,
        0.2268,
        0.1648,
        0.1115,
        0.0651,
        0.0236,
        -0.0135,
        -0.0474,
        -0.0784,
        -0.1071,
        -0.1337,
        -0.1585,
        -0.1818,
        -0.2037,
        -0.2243,
        -0.2438,
        -0.2623,
        -0.2799,
        -0.2965,
        -0.3125,
        -0.3276
      ],
      [
        0.6236,
        0.4349,
        0.3086,
        0.2132,
        0.1364,
        0.0691,
        0.0113,
        -0.0389,
        -0.0838,
        -0.1239,
        -0.1606,
        -0.1941,
        -0.2251,
        -0.2538,
        -0.2807,
        -0.3058,
        -0.3296,
        -0.3519,
        -0.3732,
        -0.3933,
        -0.4125,
        -0.4308,
        -0.4483,
        -0.465
      ],
      [
        0.5778,
        0.377,
        0.243,
        0.142,
        0.061,
        -0.01,
        -0.0708,
        -0.1237,
        -0.1708,
        -0.213,
        -0.2515,
        -0.2866,
        -0.3191,
        -0.3492,
        -0.3774,
        -0.4037,
        -0.4285,
        -0.4519,
        -0.4742,
        -0.4952,
        -0.5153,
        -0.5345,
        -0.5528,
        -0.5704
      ],
      [
        0.5377,
        0.328,
        0.1886,
        0.0839,
        0.0,
        -0.0733,
        -0.1361,
        -0.1906,
        -0.2392,
        -0.2826,
        -0.3221,
        -0.3582,
        -0.3916,
        -0.4225,
        -0.4514,
        -0.4784,
        -0.5038,
        -0.5278,
        -0.5506,
        -0.5722,
        -0.5928,
        -0.6123,
        -0.6311,
        -0.6491
      ],
      [
        0.5068,
        0.2914,
        0.1487,
        0.0419,
        -0.0437,
        -0.1183,
        -0.1822,
        -0.2376,
        -0.2868,
        -0.3309,
        -0.371,
        -0.4076,
        -0.4414,
        -0.4727,
        -0.5019,
        -0.5292,
        -0.555,
        -0.5793,
        -0.6023,
        -0.6241,
        -0.6449,
        -0.6647,
        -0.6837,
        -0.7018
      ],
      [
        0.4802,
        0.2608,
        0.116,
        0.0077,
        -0.0789,
        -0.1543,
        -0.2188,
        -0.2747,
        -0.3244,
        -0.3688,
        -0.4092,
        -0.446,
        -0.4801,
        -0.5116,
        -0.5411,
        -0.5685,
        -0.5945,
        -0.6189,
        -0.642,
        -0.664,
        -0.6849,
        -0.7048,
        -0.7239,
        -0.7421
      ],
      [
        0.4575,
        0.2353,
        0.0892,
        -0.02,
        -0.1072,
        -0.1831,
        -0.2479,
        -0.3041,
        -0.354,
        -0.3986,
        -0.4392,
        -0.4762,
        -0.5104,
        -0.542,
        -0.5716,
        -0.5991,
        -0.6251,
        -0.6496,
        -0.6728,
        -0.6948,
        -0.7158,
        -0.7358,
        -0.7549,
        -0.7732
      ],
      [
        0.4384,
        0.2144,
        0.0673,
        -0.0423,
        -0.1298,
        -0.206,
        -0.2711,
        -0.3274,
        -0.3774,
        -0.4222,
        -0.4628,
        -0.4999,
        -0.5342,
        -0.5658,
        -0.5954,
        -0.623,
        -0.6491,
        -0.6736,
        -0.6969,
        -0.7189,
        -0.7399,
        -0.7599,
        -0.779,
        -0.7973
      ],
      [
        0.422,
        0.1969,
        0.0493,
        -0.0607,
        -0.1484,
        -0.2248,
        -0.2899,
        -0.3463,
        -0.3964,
        -0.4412,
        -0.4819,
        -0.519,
        -0.5533,
        -0.585,
        -0.6146,
        -0.6423,
        -0.6684,
        -0.6929,
        -0.7161,
        -0.7382,
        -0.7592,
        -0.7792,
        -0.7984,
        -0.8167
      ],
      [
        0.4082,
        0.1823,
        0.0343,
        -0.0759,
        -0.1637,
        -0.2401,
        -0.3053,
        -0.3618,
        -0.4119,
        -0.4567,
        -0.4974,
        -0.5346,
        -0.5689,
        -0.6006,
        -0.6302,
        -0.6579,
        -0.6839,
        -0.7085,
        -0.7317,
        -0.7538,
        -0.7748,
        -0.7948,
        -0.814,
        -0.8323
      ],
      [
        0.3964,
        0.17,
        0.0219,
        -0.0884,
        -0.1763,
        -0.2528,
        -0.318,
        -0.3745,
        -0.4246,
        -0.4695,
        -0.5102,
        -0.5473,
        -0.5817,
        -0.6134,
        -0.643,
        -0.6706,
        -0.6967,
        -0.7213,
        -0.7446,
        -0.7666,
        -0.7876,
        -0.8076,
        -0.8268,
        -0.8451
      ]
    ]
  },
  "kinetics": {
    "overpredicts": true,
    "measuredEaKJ": 36.0,
    "measuredEaRange": [
      24.2,
      54.1
    ],
    "cascadeEaKJ": 68.8,
    "source": "Gudbrandsson et al. 2011 GCA 75, Table 5 (Si, 5-75 C)"
  },
  "cascadeEncoding": {
    "kind": "log10_ratio_to_median",
    "lo": -2.0,
    "hi": 2.0
  },
  "phEncoding": {
    "lo": 3.0,
    "hi": 10.0
  },
  "cost": {
    "floor": 0.05,
    "expDefault": 0.0,
    "haulScaleUsdT": 100.0,
    "tco2PerT": 0.289,
    "gateUsdT": 10.0,
    "truckUsdTKm": 0.12,
    "expOn": 1.0,
    "tortuosity": 1.35,
    "outcropToQuarry": 2.0,
    "gateRange": [
      0.0,
      15.0
    ],
    "gateRegional": {
      "BR": 9.0,
      "IN": 3.0,
      "US": 12.0
    },
    "gateSource": "Operator-reported quarry-fines prices (Lithos ~$12/t, Isometric <$10/t, InPlanet ~$10/t); Brazilian po de pedra R$45-50/t; Indian crusher dust ~Rs200/t. Several operators supply free, so the true floor can be $0.",
    "source": "USGS crushed-stone unit values for the gate cost; truck haul rate is an assumption. Truck only: basalt is rarely railed, and rail still needs first/last-mile truck"
  },
  "eligibility": {
    "version": "puro_v2025_isometric_v1.2",
    "socThreshold": 5.0,
    "pExcluded": 0.9,
    "pPasses": 0.1,
    "marginalDrawn": false,
    "excludedShareCropland": 0.00044,
    "marginalShareCropland": 0.532
  },
  "labels": {
    "grid": "0.1\u00b0 grid (~11 km at the equator)",
    "effectiveRes": "~10-50 km effective resolution",
    "maxZoom": 7,
    "build": "v0 preview"
  },
  "feedstock": {
    "archetype": "delivered_basalt",
    "tco2PerT": 0.289,
    "rateTHaYr": 30.0
  },
  "stats": {
    "croplandGha": 1.215,
    "cdrMedian": 0.22,
    "quarryPoints": 5295
  },
  "provenance": {
    "soil": "SoilGrids v2.0 via ISRIC WCS (pH 0-15 cm, SOC 0-5 cm + quantiles)",
    "climate": "Lembrechts monthly soil T (5-15 cm) + TerraClimate moisture",
    "cropland": "Potapov et al. 2022 percent-cropland, 3 km",
    "drainage": "WaterGAP2-2e groundwater recharge via ISIMIP3a, 0.5 deg",
    "paddy": "GRPI Landsat inundation months x SPAM2010 irrigated rice",
    "feedstock": "GLiM full-resolution basic igneous outcrop + USGS MRDS mafic-hosted stone producers, ANM SIGMINE titles (Brazil) and OSM quarries; truck-only haul, not routed",
    "substitutions": [
      "soil moisture is root-zone storage in mm, not a saturation fraction: porosity normalisation not yet applied",
      "kinetics over-predict measured basalt release; activation energy is ~2x too high (see the kinetics test)"
    ],
    "dw": {
      "value": 0.03,
      "range": [
        0.001,
        0.3
      ],
      "source": "Maher & Chamberlain 2014, Science 343, 1502 (Fig. 2 contours)"
    }
  }
};
