/* GENERATED by scripts/build_v0.py from scripts/constants.py.
   Do not edit. Edit constants.py and rebuild. */
window.ERW = {
  "grid": {
    "width": 3600,
    "height": 1400,
    "west": -179.99836080934742,
    "north": 82.71928405344525,
    "dlon": 0.09999800630262258,
    "dlat": 0.0990689892669193
  },
  "weights": {
    "reactivity": 0.25,
    "eta_dic": 0.25,
    "feedstock_cost": 0.25,
    "drainage": 0.25
  },
  "floors": {
    "reactivity": 0.0,
    "feedstock_cost": 0.05,
    "eta_dic": 0.0,
    "drainage": 0.05
  },
  "epsQuantize": 0.02,
  "aggP": 0.0,
  "criteria": [
    {
      "key": "reactivity",
      "tex": 1,
      "ch": 0,
      "label": "Weathering reactivity",
      "hint": "Palandri-Kharaka Ca+Mg release rate, relative to pH 6.5 / 15 C"
    },
    {
      "key": "eta_dic",
      "tex": 1,
      "ch": 1,
      "label": "Alkalinity retained as DIC",
      "hint": "Carbonate-equilibrium efficiency; the term Cascade omits"
    },
    {
      "key": "drainage",
      "tex": 1,
      "ch": 2,
      "label": "Drainage / transport",
      "hint": "q/(q+Dw); low where water residence limits export"
    }
  ],
  "ramp": [
    [
      0.0,
      "#3b1f4d"
    ],
    [
      0.2,
      "#3d4a8f"
    ],
    [
      0.4,
      "#2a7b8f"
    ],
    [
      0.6,
      "#3fa66b"
    ],
    [
      0.8,
      "#a8c93a"
    ],
    [
      1.0,
      "#f7e94a"
    ]
  ],
  "cascadeEncoding": {
    "kind": "log10_ratio_to_median",
    "lo": -2.0,
    "hi": 2.0
  },
  "phEncoding": {
    "lo": 3.0,
    "hi": 10.0
  },
  "eligibility": {
    "version": "puro_v2025_isometric_v1.2",
    "socThreshold": 5.0,
    "pExcluded": 0.9,
    "pPasses": 0.1
  },
  "labels": {
    "grid": "0.1\u00b0 grid (~11 km at the equator)",
    "effectiveRes": "~10-50 km effective resolution",
    "maxZoom": 7,
    "build": "v0 preview"
  },
  "feedstock": {
    "archetype": "delivered_basalt",
    "tco2PerT": 0.289,
    "rateTHaYr": 20.0
  },
  "stats": {
    "croplandGha": 1.215,
    "cdrMedian": 0.32
  },
  "provenance": {
    "soil": "SoilGrids v2.0 via ISRIC WCS (pH 0-15 cm, SOC 0-5 cm + quantiles)",
    "climate": "WorldClim 2.1 BIO1 / BIO12, 10 arc-min",
    "cropland": "GLAD global cropland probability (Potapov et al.)",
    "substitutions": [
      "AIR temperature stands in for monthly SOIL temperature",
      "PRECIPITATION stands in for a soil-moisture climatology",
      "no paddy mask yet, so all cells use the unsaturated soil pCO2",
      "no feedstock or haul-cost layer yet"
    ]
  }
};
