/* GENERATED by scripts/build_v0.py from scripts/constants.py.
   Do not edit. Edit constants.py and rebuild. */
window.ERW = {
  "grid": {
    "width": 3600,
    "height": 1400,
    "west": -179.99836080934742,
    "north": 82.71928405344525,
    "dlon": 0.09999800630262258,
    "dlat": 0.0990689892669193
  },
  "terms": [
    {
      "key": "reactivity",
      "label": "Dissolution rate",
      "hint": "Palandri-Kharaka Ca+Mg release, relative to pH 6.5 / 15 C"
    },
    {
      "key": "eta_dic",
      "label": "Alkalinity retained as DIC",
      "hint": "Carbonate-equilibrium efficiency; the term Cascade omits"
    },
    {
      "key": "drainage",
      "label": "Drainage / transport",
      "hint": "q/(q+Dw) on WaterGAP recharge; low where water residence limits export"
    }
  ],
  "epsQuantize": 0.02,
  "aggP": 0.0,
  "criteria": [
    {
      "key": "reactivity",
      "tex": 1,
      "ch": 0,
      "label": "Weathering reactivity",
      "hint": "Palandri-Kharaka Ca+Mg release rate, relative to pH 6.5 / 15 C"
    },
    {
      "key": "eta_dic",
      "tex": 1,
      "ch": 1,
      "label": "Alkalinity retained as DIC",
      "hint": "Carbonate-equilibrium efficiency; the term Cascade omits"
    },
    {
      "key": "drainage",
      "tex": 1,
      "ch": 2,
      "label": "Drainage / transport",
      "hint": "q/(q+Dw); low where water residence limits export"
    }
  ],
  "ramp": [
    [
      0.0,
      "#3b1f4d"
    ],
    [
      0.2,
      "#3d4a8f"
    ],
    [
      0.4,
      "#2a7b8f"
    ],
    [
      0.6,
      "#3fa66b"
    ],
    [
      0.8,
      "#a8c93a"
    ],
    [
      1.0,
      "#f7e94a"
    ]
  ],
  "cdrKnots": [
    [
      0.02,
      0.0
    ],
    [
      0.1,
      0.2
    ],
    [
      0.5,
      0.4
    ],
    [
      1.5,
      0.6
    ],
    [
      4.0,
      0.8
    ],
    [
      10.0,
      1.0
    ]
  ],
  "cdrNegligible": 0.02,
  "dissolvedFracAtRef": 0.25,
  "dissolvedFracObserved": [
    0.15,
    0.56
  ],
  "termExponent": {
    "default": 1.0,
    "range": [
      0.0,
      1.0
    ]
  },
  "cdrPerFrac": 5.79412,
  "l1Enc": {
    "lo": -3.0,
    "hi": 3.0
  },
  "psd": {
    "refD50": 150.0,
    "refWidth": 1.5,
    "d50Range": [
      40.0,
      700.0
    ],
    "widthRange": [
      0.7,
      2.5
    ],
    "refSsa": 0.02572,
    "lambdaDefault": 27.5,
    "lambdaMeasured": 27.5,
    "lambdaBasis": "Gudbrandsson et al. 2011: 45-125 um sieve fraction with fines removed, 0.703 m2/g krypton BET, implied d80 109 um",
    "betMeasured": 0.703,
    "refWidthNarrowForCrush": true,
    "lambdaRange": [
      1.0,
      100.0
    ],
    "deliveryRangeUm": [
      67.0,
      600.0
    ],
    "deliveryP50": {
      "mati": 600.0,
      "terradot": 120.0,
      "lithos": 67.0
    },
    "refWidthAssumed": true,
    "d50Grid": [
      40.0,
      68.7,
      97.4,
      126.1,
      154.8,
      183.5,
      212.2,
      240.9,
      269.6,
      298.3,
      327.0,
      355.7,
      384.3,
      413.0,
      441.7,
      470.4,
      499.1,
      527.8,
      556.5,
      585.2,
      613.9,
      642.6,
      671.3,
      700.0
    ],
    "widthGrid": [
      0.7,
      0.85,
      1.0,
      1.15,
      1.3,
      1.45,
      1.6,
      1.75,
      1.9,
      2.05,
      2.2,
      2.35,
      2.5
    ],
    "shiftTable": [
      [
        0.7779,
        0.6437,
        0.5547,
        0.4877,
        0.4341,
        0.3893,
        0.351,
        0.3175,
        0.288,
        0.2615,
        0.2377,
        0.2161,
        0.1963,
        0.1781,
        0.1614,
        0.1459,
        0.1314,
        0.118,
        0.1054,
        0.0936,
        0.0825,
        0.0721,
        0.0622,
        0.0529
      ],
      [
        0.7301,
        0.5733,
        0.4691,
        0.3906,
        0.3276,
        0.2748,
        0.2294,
        0.1896,
        0.1541,
        0.1221,
        0.093,
        0.0664,
        0.0418,
        0.0191,
        -0.002,
        -0.0218,
        -0.0402,
        -0.0575,
        -0.0738,
        -0.0891,
        -0.1036,
        -0.1173,
        -0.1303,
        -0.1426
      ],
      [
        0.6805,
        0.5042,
        0.3871,
        0.299,
        0.2282,
        0.169,
        0.1181,
        0.0734,
        0.0335,
        -0.0025,
        -0.0353,
        -0.0654,
        -0.0932,
        -0.1191,
        -0.1433,
        -0.1659,
        -0.1872,
        -0.2073,
        -0.2264,
        -0.2444,
        -0.2615,
        -0.2777,
        -0.2932,
        -0.3079
      ],
      [
        0.6327,
        0.4404,
        0.313,
        0.2172,
        0.1404,
        0.0762,
        0.021,
        -0.0274,
        -0.0706,
        -0.1095,
        -0.1449,
        -0.1775,
        -0.2076,
        -0.2356,
        -0.2618,
        -0.2863,
        -0.3095,
        -0.3313,
        -0.3521,
        -0.3717,
        -0.3905,
        -0.4084,
        -0.4255,
        -0.4418
      ],
      [
        0.5888,
        0.3839,
        0.2486,
        0.1472,
        0.0659,
        -0.0019,
        -0.0601,
        -0.1112,
        -0.1566,
        -0.1976,
        -0.2349,
        -0.2691,
        -0.3007,
        -0.3301,
        -0.3576,
        -0.3833,
        -0.4076,
        -0.4306,
        -0.4523,
        -0.473,
        -0.4927,
        -0.5115,
        -0.5295,
        -0.5468
      ],
      [
        0.5496,
        0.3353,
        0.1943,
        0.0889,
        0.0047,
        -0.0656,
        -0.1258,
        -0.1786,
        -0.2255,
        -0.2678,
        -0.3062,
        -0.3415,
        -0.3741,
        -0.4043,
        -0.4326,
        -0.4591,
        -0.484,
        -0.5076,
        -0.53,
        -0.5512,
        -0.5714,
        -0.5908,
        -0.6093,
        -0.627
      ],
      [
        0.5156,
        0.2945,
        0.1496,
        0.0415,
        -0.0447,
        -0.1165,
        -0.178,
        -0.2318,
        -0.2796,
        -0.3227,
        -0.3618,
        -0.3977,
        -0.4308,
        -0.4615,
        -0.4902,
        -0.5172,
        -0.5425,
        -0.5664,
        -0.5891,
        -0.6106,
        -0.6312,
        -0.6508,
        -0.6695,
        -0.6875
      ],
      [
        0.4865,
        0.2606,
        0.1131,
        0.0033,
        -0.0841,
        -0.1568,
        -0.2191,
        -0.2735,
        -0.3218,
        -0.3652,
        -0.4047,
        -0.4409,
        -0.4744,
        -0.5054,
        -0.5343,
        -0.5614,
        -0.587,
        -0.6111,
        -0.6339,
        -0.6556,
        -0.6763,
        -0.696,
        -0.7149,
        -0.733
      ],
      [
        0.4618,
        0.2326,
        0.0835,
        -0.0272,
        -0.1154,
        -0.1886,
        -0.2513,
        -0.306,
        -0.3546,
        -0.3983,
        -0.438,
        -0.4744,
        -0.5079,
        -0.5391,
        -0.5682,
        -0.5954,
        -0.621,
        -0.6452,
        -0.6681,
        -0.6899,
        -0.7107,
        -0.7304,
        -0.7494,
        -0.7675
      ],
      [
        0.441,
        0.2097,
        0.0596,
        -0.0518,
        -0.1403,
        -0.2139,
        -0.2767,
        -0.3316,
        -0.3804,
        -0.4242,
        -0.464,
        -0.5005,
        -0.5341,
        -0.5653,
        -0.5944,
        -0.6217,
        -0.6474,
        -0.6716,
        -0.6946,
        -0.7164,
        -0.7372,
        -0.757,
        -0.7759,
        -0.7941
      ],
      [
        0.4235,
        0.1909,
        0.0401,
        -0.0716,
        -0.1604,
        -0.2341,
        -0.297,
        -0.352,
        -0.4009,
        -0.4447,
        -0.4846,
        -0.5211,
        -0.5547,
        -0.586,
        -0.6151,
        -0.6425,
        -0.6682,
        -0.6924,
        -0.7154,
        -0.7372,
        -0.758,
        -0.7778,
        -0.7968,
        -0.815
      ],
      [
        0.4088,
        0.1753,
        0.0242,
        -0.0877,
        -0.1766,
        -0.2504,
        -0.3134,
        -0.3685,
        -0.4173,
        -0.4612,
        -0.5011,
        -0.5376,
        -0.5713,
        -0.6026,
        -0.6317,
        -0.659,
        -0.6848,
        -0.709,
        -0.732,
        -0.7538,
        -0.7746,
        -0.7945,
        -0.8134,
        -0.8316
      ],
      [
        0.3964,
        0.1624,
        0.0111,
        -0.1009,
        -0.1899,
        -0.2637,
        -0.3268,
        -0.3819,
        -0.4307,
        -0.4747,
        -0.5146,
        -0.5511,
        -0.5848,
        -0.616,
        -0.6452,
        -0.6725,
        -0.6982,
        -0.7225,
        -0.7455,
        -0.7673,
        -0.7881,
        -0.808,
        -0.8269,
        -0.8451
      ]
    ]
  },
  "kinetics": {
    "overpredicts": true,
    "measuredEaKJ": 36.0,
    "measuredEaRange": [
      24.2,
      54.1
    ],
    "cascadeEaKJ": 68.8,
    "source": "Gudbrandsson et al. 2011 GCA 75, Table 5 (Si, 5-75 C)"
  },
  "cascadeEncoding": {
    "kind": "log10_ratio_to_median",
    "lo": -2.0,
    "hi": 2.0
  },
  "phEncoding": {
    "lo": 3.0,
    "hi": 10.0
  },
  "cost": {
    "floor": 0.05,
    "expDefault": 0.0,
    "haulScaleUsdT": 100.0,
    "tco2PerT": 0.289,
    "gateUsdT": 10.0,
    "truckUsdTKm": 0.12,
    "expOn": 1.0,
    "tortuosity": 1.35,
    "outcropToQuarry": 2.0,
    "gateRange": [
      0.0,
      15.0
    ],
    "gateRegional": {
      "BR": 9.0,
      "IN": 3.0,
      "US": 12.0
    },
    "gateSource": "Operator-reported quarry-fines prices (Lithos ~$12/t, Isometric <$10/t, InPlanet ~$10/t); Brazilian po de pedra R$45-50/t; Indian crusher dust ~Rs200/t. Several operators supply free, so the true floor can be $0.",
    "source": "USGS crushed-stone unit values for the gate cost; truck haul rate is an assumption. Truck only: basalt is rarely railed, and rail still needs first/last-mile truck"
  },
  "eligibility": {
    "version": "puro_v2025_isometric_v1.2",
    "socThreshold": 5.0,
    "pExcluded": 0.9,
    "pPasses": 0.1
  },
  "labels": {
    "grid": "0.1\u00b0 grid (~11 km at the equator)",
    "effectiveRes": "~10-50 km effective resolution",
    "maxZoom": 7,
    "build": "v0 preview"
  },
  "feedstock": {
    "archetype": "delivered_basalt",
    "tco2PerT": 0.289,
    "rateTHaYr": 20.0
  },
  "stats": {
    "croplandGha": 1.215,
    "cdrMedian": 0.8,
    "quarryPoints": 5188
  },
  "provenance": {
    "soil": "SoilGrids v2.0 via ISRIC WCS (pH 0-15 cm, SOC 0-5 cm + quantiles)",
    "climate": "Lembrechts monthly soil T (5-15 cm) + TerraClimate moisture",
    "cropland": "Potapov et al. 2022 percent-cropland, 3 km",
    "drainage": "WaterGAP2-2e groundwater recharge via ISIMIP3a, 0.5 deg",
    "paddy": "GRPI Landsat inundation months x SPAM2010 irrigated rice",
    "feedstock": "GLiM full-resolution basic igneous outcrop + USGS MRDS mafic-hosted stone producers; truck/rail haul, not routed",
    "substitutions": [
      "soil moisture is root-zone storage in mm, not a saturation fraction: porosity normalisation not yet applied",
      "kinetics over-predict measured basalt release; activation energy is ~2x too high (see the kinetics test)"
    ],
    "dw": {
      "value": 0.03,
      "range": [
        0.001,
        0.3
      ],
      "source": "Maher & Chamberlain 2014, Science 343, 1502 (Fig. 2 contours)"
    }
  }
};
